name: Shopify Update Workflow

on:
  schedule:
    - cron: '0 8 * * *'  # Ejecutar a las 09:00 todos los días
  workflow_dispatch:  # Permitir ejecución manual

jobs:
  update-shopify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run update script
        env:
          API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          SHOP_NAME: ${{ secrets.SHOPIFY_SHOP_NAME }}
        run: |
          python update_shopify.py
